version: '3.8'

services:
  nodejs_app:
    image: node:${NODE_IMAGE_TAG}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - ${NODE_PORT}:3000
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    environment:
      NODE_ENV: ${NODE_ENV}
    env_file:
      - ./.env
    command: sh -c "npm install && npm start"
